name: Tests

on:
  push:
    branches: [ trunk]
  pull_request:
    branches: [ trunk]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run smoke tests
        run: ./test/smoke.sh
      - name: Run main class detection tests
        run: ./test/main-class-detection.sh
