name: Tests

on:
  push:
    branches: [ trunk]
  pull_request:
    branches: [ trunk]

jobs:
  vanity:
    runs-on: ubuntu-latest

    steps:
      - name: Run smoke tests
        run: ls -al && ./test/smoke.sh
