name: Vanity URLs for all tagged versions

on:
  push:
    tags:
      - '*'

jobs:
  vanity:
    runs-on: ubuntu-latest

    steps:
      - name: Main script
        run: echo "${{ github.ref }}" | sed 's|refs/tags/||' | ( read version; curl -i https://git.io -F "url=https://raw.githubusercontent.com/tsk-tsk/tsk-tsk/${version}/tsk" -F "code=tsk-${version}" )
      - name: Bootloader script
        run: echo "${{ github.ref }}" | sed 's|refs/tags/||' | ( read version; curl -i https://git.io -F "url=https://raw.githubusercontent.com/tsk-tsk/tsk-tsk/${version}/boot-tsk" -F "code=boot-tsk-${version}" )
